import dotenv from 'dotenv';

dotenv.config();

export default {
  apps: [
    {
      name: 'backend',
      script: './dist/src/main.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: process.env.NODE_ENV || 'development',
        APP_NAME: process.env.APP_NAME,
        APP_KEY: process.env.APP_KEY,
        PORT: process.env.PORT,
        APP_URL: process.env.APP_URL,
        CLIENT_APP_URL: process.env.CLIENT_APP_URL,
        SESSION_SECRET: process.env.SESSION_SECRET,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRY: process.env.JWT_EXPIRY,
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PASSWORD: process.env.REDIS_PASSWORD,
        REDIS_PORT: process.env.REDIS_PORT,
        MAIL_HOST: process.env.MAIL_HOST,
        MAIL_USERNAME: process.env.MAIL_USERNAME,
        MAIL_PASSWORD: process.env.MAIL_PASSWORD,
        MAIL_FROM_ADDRESS: process.env.MAIL_FROM_ADDRESS,
        MAIL_FROM_NAME: process.env.MAIL_FROM_NAME,
        GOOGLE_APP_ID: process.env.GOOGLE_APP_ID,
        GOOGLE_APP_SECRET: process.env.GOOGLE_APP_SECRET,
        GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,
        FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
        FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
        FACEBOOK_CALLBACK_URL: process.env.FACEBOOK_CALLBACK_URL,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_DEFAULT_REGION: process.env.AWS_DEFAULT_REGION,
        AWS_BUCKET: process.env.AWS_BUCKET,
        AWS_URL: process.env.AWS_URL,
        AWS_ENDPOINT: process.env.AWS_ENDPOINT,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
        PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
        PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET,
        PAYPAL_SANDBOX: process.env.PAYPAL_SANDBOX,
        JUMIO_API_TOKEN: process.env.JUMIO_API_TOKEN,
        JUMIO_API_SECRET: process.env.JUMIO_API_SECRET,
        JUMIO_BASE_URL: process.env.JUMIO_BASE_URL,
        JUMIO_CALLBACK_URL: process.env.JUMIO_CALLBACK_URL,
        OPENAI_API_KEY: process.env.OPENAI_API_KEY,
        SYSTEM_USERNAME: process.env.SYSTEM_USERNAME,
        SYSTEM_EMAIL: process.env.SYSTEM_EMAIL,
        SYSTEM_PASSWORD: process.env.SYSTEM_PASSWORD,
      },
    },
  ],

  deploy: {
    production: {
      user: 'ubuntu',
      host: 'your-ec2-ip',
      key: '/path/to/key.pem',
      ref: 'origin/main',
      repo: 'git@github.com:your-repo.git',
      path: '/var/www/backend',
      'post-deploy': 'yarn install && yarn build && pm2 startOrRestart ecosystem.config.js',
      'pre-deploy-local': 'echo "Deploying to production"',
    },
  },
};
